<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Tutup_todayMnaClose</name>
   <tag></tag>
   <elementGuidId>65dedfd8-7672-4b61-80cf-8d84f02e88f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='todayMnaClose']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#todayMnaClose</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1216b732-af35-4bbb-a173-0238691009fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popup-adv__close</value>
      <webElementGuid>b26f8275-80c5-4e4f-b20d-1c65bb48096f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>todayMnaClose</value>
      <webElementGuid>67ffcaa1-95d0-44df-a7ec-3faee20c6b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;todayMnaClose&quot;)</value>
      <webElementGuid>0564405a-01a6-44b6-8c99-4c7f340799a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='todayMnaClose']</value>
      <webElementGuid>f11c7c4d-4211-4bc1-b1b9-4f707b845fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='position000021271']/i</value>
      <webElementGuid>498f0628-24b7-49c9-9cfc-ddae500b13e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/i</value>
      <webElementGuid>d1e78d6d-709a-4ce2-8a9b-36a818d6443c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'todayMnaClose']</value>
      <webElementGuid>ea317396-f172-4bda-9b1f-992ec877abd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
