<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Item</name>
   <tag></tag>
   <elementGuidId>3b6c7983-7b5a-4d69-b25f-acc6faa54b25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='productResult']/ul/li/div/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.prd_thumb.lazy-prd_search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d0b1ed1d-650c-4d4b-849c-b46180d2214c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prd_thumb lazy-prd_search</value>
      <webElementGuid>940c8073-e0b0-4924-b56b-4ca0ba8055a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original</name>
      <type>Main</type>
      <value>https://dxclnrbvyw82b.cloudfront.net/images/product/web/92/27/86/00/0/000000862792_03_320.jpg</value>
      <webElementGuid>a3885734-1f22-4987-b1de-5fbf5f9e375e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ori</name>
      <type>Main</type>
      <value>https://dxclnrbvyw82b.cloudfront.net/images/product/web/92/27/86/00/0/000000862792_03_320.jpg</value>
      <webElementGuid>a7733627-312d-4bdf-9413-d60d44dc7ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.src = '/static-root/images//common/no_img_320x320.jpg';</value>
      <webElementGuid>82db546c-db35-4b8c-a277-bae4adf4d43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>cocoa jewelry Kalung Wanita Korea - Chain Gold Color</value>
      <webElementGuid>2888e6ba-f5d8-4793-89ac-0534220ef269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>cocoa jewelry Kalung Wanita Korea - Chain Gold Color</value>
      <webElementGuid>736f1032-8475-469a-8df3-26a19509ca1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dxclnrbvyw82b.cloudfront.net/images/product/web/92/27/86/00/0/000000862792_03_320.jpg</value>
      <webElementGuid>a92e5d14-6e04-4d38-8e41-35eddc9b8a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productResult&quot;)/ul[1]/li[1]/div[@class=&quot;prd_box&quot;]/div[@class=&quot;wrap&quot;]/div[@class=&quot;right_area&quot;]/div[@class=&quot;img_box&quot;]/a[@class=&quot;box_link&quot;]/img[@class=&quot;prd_thumb lazy-prd_search&quot;]</value>
      <webElementGuid>49a8b3cf-b18e-4e8a-92f2-d4e1ca021faf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productResult']/ul/li/div/div/div/div/a/img</value>
      <webElementGuid>a51114bf-4cc1-40af-a56d-ca1a0e58050b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='cocoa jewelry Kalung Wanita Korea - Chain Gold Color']</value>
      <webElementGuid>be46f5f6-45de-4520-8a22-5ee01780e1a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div/div/a/img</value>
      <webElementGuid>d40e5725-7ea8-4755-8a49-6d59ca7f85f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'cocoa jewelry Kalung Wanita Korea - Chain Gold Color' and @title = 'cocoa jewelry Kalung Wanita Korea - Chain Gold Color' and @src = 'https://dxclnrbvyw82b.cloudfront.net/images/product/web/92/27/86/00/0/000000862792_03_320.jpg']</value>
      <webElementGuid>57cd8a07-b1e5-4b8b-9ce6-9f1b171277b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
