<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_query</name>
   <tag></tag>
   <elementGuidId>b0898f0c-f8fd-4eb8-bf74-b4af47150485</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='headerQuery']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headerQuery</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae10c563-b3e3-4c30-b966-56356409e5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>cc06d932-1a57-4c4a-81bd-6baa57a76573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>query</value>
      <webElementGuid>ca37d8d0-afde-4019-aa69-5a686e50c418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headerQuery</value>
      <webElementGuid>cb40672b-0b50-4b53-87a0-a65c99a24296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please enter search words</value>
      <webElementGuid>4e8d54e9-aa67-46c4-a6e0-29cb2979098e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Apa yang kamu cari hari ini?</value>
      <webElementGuid>4b987a61-b54d-46d1-a8d5-6ef2ad1d0bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:indolotte.front.ec.search.search_header.makeHeader()</value>
      <webElementGuid>83d21727-2f0f-45f4-b7d3-65b1842c8717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>javascript:indolotte.front.ec.search.search_header.pressCheckHeader((event),this);</value>
      <webElementGuid>90992500-cf0b-46c3-a578-2f94cae1aafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>77dad985-38e8-4139-b887-313f3dd0339b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerQuery&quot;)</value>
      <webElementGuid>ed36d839-079e-42db-9bc8-66a9495a3284</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='headerQuery']</value>
      <webElementGuid>d3a60292-eaa5-412e-81bd-471e71ee9efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchHeaderForm']/div/input</value>
      <webElementGuid>1c605aa2-5e7c-4b9f-8e5f-4e4232e2d27a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>f3db32c0-4e66-4105-8c17-6f9d8d49abab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @name = 'query' and @id = 'headerQuery' and @title = 'Please enter search words' and @placeholder = 'Apa yang kamu cari hari ini?']</value>
      <webElementGuid>84aa2ed0-8a9f-48d1-9b23-56ad8dd6aeb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
