<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BCA</name>
   <tag></tag>
   <elementGuidId>ba523bac-2f1c-4a36-94bd-8d8995ea36cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@onclick='$.fancybox.close();'])[16]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f0efa4a9-a196-493e-8712-e078b3ee1557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cont</value>
      <webElementGuid>29f3ff75-0f9a-40ae-8ed7-8a092e529b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$.fancybox.close();</value>
      <webElementGuid>cfd77cda-b5c3-4d3c-a59b-9dcf45bd92c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>                                                                                                                                                                                                                     BCA                                                                              </value>
      <webElementGuid>4b5db2e7-1847-4c67-8627-8ab0663e9846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;virtualAccountListLayer&quot;)/li[6]/div[@class=&quot;cont&quot;]</value>
      <webElementGuid>d92baf2d-82e2-49b1-9bdd-b34c1a37fd35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@onclick='$.fancybox.close();'])[16]</value>
      <webElementGuid>37471568-6988-456c-87e9-a7b07709d1a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='virtualAccountListLayer']/li[6]/div</value>
      <webElementGuid>de5b3d72-9087-4f4a-b028-82634115a39e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permata'])[1]/following::div[1]</value>
      <webElementGuid>7cb5fef9-2bee-44ca-bca5-ac35f2f4e739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DANAMON'])[1]/following::div[2]</value>
      <webElementGuid>d1e1e5c7-51c7-4eda-8122-1069f4d7a23e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maybank'])[1]/preceding::div[1]</value>
      <webElementGuid>bd67e800-5129-44eb-8569-5cb1dfa8606a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[6]/div</value>
      <webElementGuid>de59c2df-3a2f-438f-8491-d32c7567b58b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '                                                                                                                                                                                                                     BCA                                                                              ' or . = '                                                                                                                                                                                                                     BCA                                                                              ')]</value>
      <webElementGuid>e936f54c-5853-4603-97ed-9075650934f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
