<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Payment_method</name>
   <tag></tag>
   <elementGuidId>108f6140-d016-4c09-b757-ff74ecf72932</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='viewOrderPymtMethod']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#viewOrderPymtMethod</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'viewOrderPymtMethod' and (text() = 'Transfer' or . = 'Transfer')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fcf415cc-e350-40e5-b904-0fb8cf499382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>viewOrderPymtMethod</value>
      <webElementGuid>efe01955-5878-45bf-8db5-abf0c6271294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transfer</value>
      <webElementGuid>707416cc-e2d5-4770-a778-4c8f025afbce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;viewOrderPymtMethod&quot;)</value>
      <webElementGuid>36298900-6af9-42eb-bfcd-a21559ee852e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='viewOrderPymtMethod']</value>
      <webElementGuid>34af4fad-af8e-4f45-a2c4-6c3db8afd1b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='viewOrderStatusLayer']/div[2]/table/tbody/tr[3]/td/span</value>
      <webElementGuid>276ecbbc-930e-4270-8491-60b5bd6465d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Pembayaran'])[1]/following::span[1]</value>
      <webElementGuid>30fd8150-3ebf-4fe7-94b9-b66b8f8b5e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Pesanan'])[1]/following::span[1]</value>
      <webElementGuid>de47567f-ed2a-41e6-8931-80d7b13cde7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu Pembayaran'])[2]/preceding::span[1]</value>
      <webElementGuid>8e8259cd-84df-446a-a3ac-ace510c21917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Transfer']/parent::*</value>
      <webElementGuid>2537e11d-2e9b-4271-a4b9-358aa4fc5d68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span</value>
      <webElementGuid>525067a4-f95a-4ecc-9f54-63d570be97d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'viewOrderPymtMethod' and (text() = 'Transfer' or . = 'Transfer')]</value>
      <webElementGuid>27adcac2-2005-48c4-8623-8503cbb74e29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
